### PR TITLE
Update for DRF 2.0

### PR DESCRIPTION
**Pull request by jaycle**
Updates README.md with tested versions for DRF, django and python.
Test updated for DRF 2.0 to provide required on_delete argument.

### CODE REVIEW

**Comment by jaycle** [comment]
I've never messed with Travis but I should probably do something to tox.ini and .travis.yml?

**Comment by heywbj** [comment]
I agree that the test should be added to tox, and I am not sure I understand why "CASCADE" is necessary behavior in the test. In what sense is this on_delete behavior necessary for Django 2.0 compatibility?

**Comment by jaycle** [comment]
`on_delete` is now required in Django 2.0, yes:

> The on_delete argument for ForeignKey and OneToOneField is now required in models and migrations. Consider squashing migrations so that you have fewer of them to update.

https://docs.djangoproject.com/en/2.0/releases/2.0/

**Comment by ferndot** [comment]
Is this still being maintained?

**Comment by heywbj** [comment]
Since the change is only to a test and to documentation, it doesn't affect the functionality of the package. In any case the test doesn't write to any database either.

What functionality does this update achieve?

**Comment by jaycle** [comment]
No functionality. Just to help the Readme stay up to date. What else should be added to this PR?

**Comment by ferndot** [comment]
It would probably be nice to have tests against Django 2.0 and 2.1 in `tox.ini`.

**Pull request merged**
